# Maps Issue Forms dropdown selections to labels.
# See https://github.com/redhat-plumbers-in-action/advanced-issue-labeler for syntax.
# Both Issue Forms share priority mapping; append area-specific policy here.
policy:
  - template:
      - bug.yml
      - feature.yml
    section:
      - id: [priority]
        block-list: []
        label:
          - name: 'priority:high'
            keys: ['high']
          - name: 'priority:medium'
            keys: ['medium']
          - name: 'priority:low'
            keys: ['low']
