name: Apply labels from issue form

on:
  issues:
    types:
      - opened
      - edited

permissions:
  issues: write

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Parse bug.yml
        id: parse-bug
        uses: stefanbuck/github-issue-parser@v3
        with:
          template-path: .github/ISSUE_TEMPLATE/bug.yml
        continue-on-error: true

      - name: Apply labels for bug
        if: steps.parse-bug.outcome == 'success'
        uses: redhat-plumbers-in-action/advanced-issue-labeler@v2
        with:
          issue-form: ${{ steps.parse-bug.outputs.jsonString }}
          template: bug.yml
          section: priority
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Parse feature.yml
        id: parse-feature
        uses: stefanbuck/github-issue-parser@v3
        with:
          template-path: .github/ISSUE_TEMPLATE/feature.yml
        continue-on-error: true

      - name: Apply labels for feature
        if: steps.parse-feature.outcome == 'success'
        uses: redhat-plumbers-in-action/advanced-issue-labeler@v2
        with:
          issue-form: ${{ steps.parse-feature.outputs.jsonString }}
          template: feature.yml
          section: priority
          token: ${{ secrets.GITHUB_TOKEN }}
